AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  dop-serverless-2026

Parameters:
  Stage:
    Type: String
    AllowedValues:
      - dev
      - qa
      - prod
    Description: The stage of the application (e.g., qa, prod)

Resources:
  TaskApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "task-api-${Stage}"
      StageName: !Ref Stage
      Cors:
        AllowMethods: "'GET,POST,PUT,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Api-Key'"
        AllowOrigin: "'*'"
      Auth:
        ApiKeyRequired: true
        UsagePlan:
          CreateUsagePlan: PER_API
          UsagePlanName: !Sub "task-api-usage-plan-${Stage}"
          Quota:
            Limit: 1000
            Period: DAY
          Throttle:
            BurstLimit: 50
            RateLimit: 10

  HealthCheckFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Health check endpoint for the application
      CodeUri: src/health_check/
      Handler: app.lambda_handler
      Runtime: python3.12
      AutoPublishAlias: live
      DeploymentPreference:
        Type: Canary10Percent5Minutes
        Alarms:
          - !Ref HealthCheckFunctionErrorAlarm
      Events:
        HealthCheck:
          Type: Api
          Properties:
              RestApiId: !Ref TaskApi
              Path: /health
              Method: get
      Tags:
        createdBy: SAM

  CreateTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Create task endpoint for the application
      CodeUri: src/create_task/
      Handler: app.lambda_handler
      Runtime: python3.12
      AutoPublishAlias: live
      DeploymentPreference:
        Type: Canary10Percent5Minutes
        Alarms:
          - !Ref CreateTaskFunctionErrorAlarm
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TaskDynamoDBTable
      Events:
        CreateTask:
          Type: Api
          Properties:
              RestApiId: !Ref TaskApi
              Path: /create_task
              Method: post
      Environment:
        Variables:
          TABLE_NAME: !Ref TaskDynamoDBTable
      Tags:
        createdBy: SAM
        stage: !Ref Stage

  GetTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Get a single task by task_id
      CodeUri: src/get_task/
      Handler: app.lambda_handler
      Runtime: python3.12
      AutoPublishAlias: live
      DeploymentPreference:
        Type: Canary10Percent5Minutes
        Alarms:
          - !Ref GetTaskFunctionErrorAlarm
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref TaskDynamoDBTable
      Events:
        GetTask:
          Type: Api
          Properties:
              RestApiId: !Ref TaskApi
              Path: /tasks/{task_id}
              Method: get
      Environment:
        Variables:
          TABLE_NAME: !Ref TaskDynamoDBTable
      Tags:
        createdBy: SAM
        stage: !Ref Stage

  ListTasksFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: List all tasks
      CodeUri: src/list_task/
      Handler: app.lambda_handler
      Runtime: python3.12
      AutoPublishAlias: live
      DeploymentPreference:
        Type: Canary10Percent5Minutes
        Alarms:
          - !Ref ListTasksFunctionErrorAlarm
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref TaskDynamoDBTable
      Events:
        ListTask:
          Type: Api
          Properties:
              RestApiId: !Ref TaskApi
              Path: /tasks
              Method: get
      Environment:
        Variables:
          TABLE_NAME: !Ref TaskDynamoDBTable
      Tags:
        createdBy: SAM
        stage: !Ref Stage

  UpdateTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Update the status of an existing task
      CodeUri: src/update_task/
      Handler: app.lambda_handler
      Runtime: python3.12
      AutoPublishAlias: live
      DeploymentPreference:
        Type: Canary10Percent5Minutes
        Alarms:
          - !Ref UpdateTaskFunctionErrorAlarm
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TaskDynamoDBTable
      Events:
        UpdateTask:
          Type: Api
          Properties:
              RestApiId: !Ref TaskApi
              Path: /tasks/{task_id}
              Method: put
      Environment:
        Variables:
          TABLE_NAME: !Ref TaskDynamoDBTable
      Tags:
        createdBy: SAM
        stage: !Ref Stage

  TaskDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "tasks-${Stage}"
      AttributeDefinitions:
        - AttributeName: task_id
          AttributeType: S
      KeySchema:
        - AttributeName: task_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: createdBy
          Value: SAM
        - Key: stage
          Value: !Ref Stage

  HealthCheckFunctionErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "HealthCheckFunction-Errors-${Stage}"
      Namespace: AWS/Lambda
      MetricName: Errors
      Dimensions:
        - Name: FunctionName
          Value: !Ref HealthCheckFunction
        - Name: Resource
          Value: !Sub "${HealthCheckFunction}:live"
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching

  CreateTaskFunctionErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "CreateTaskFunction-Errors-${Stage}"
      Namespace: AWS/Lambda
      MetricName: Errors
      Dimensions:
        - Name: FunctionName
          Value: !Ref CreateTaskFunction
        - Name: Resource
          Value: !Sub "${CreateTaskFunction}:live"
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching

  GetTaskFunctionErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "GetTaskFunction-Errors-${Stage}"
      Namespace: AWS/Lambda
      MetricName: Errors
      Dimensions:
        - Name: FunctionName
          Value: !Ref GetTaskFunction
        - Name: Resource
          Value: !Sub "${GetTaskFunction}:live"
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching

  ListTasksFunctionErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "ListTasksFunction-Errors-${Stage}"
      Namespace: AWS/Lambda
      MetricName: Errors
      Dimensions:
        - Name: FunctionName
          Value: !Ref ListTasksFunction
        - Name: Resource
          Value: !Sub "${ListTasksFunction}:live"
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching

  UpdateTaskFunctionErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "UpdateTaskFunction-Errors-${Stage}"
      Namespace: AWS/Lambda
      MetricName: Errors
      Dimensions:
        - Name: FunctionName
          Value: !Ref UpdateTaskFunction
        - Name: Resource
          Value: !Sub "${UpdateTaskFunction}:live"
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching

Outputs:
  TaskApiUrl:
    Description: URL for the Task API
    Value: !Sub "https://${TaskApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/${Stage}/"
